package org.sid.secservice.sec.entities.enumeration;

public enum EnumEtat {
    ENCOURS, ABANDON,IMPOSSIBLE, SUSPENSION,POURSOUTENANCE ,VALIDE, NONVALIDE, EXCLU, ADMISSIBLE, REDOUBLE, VALIDEPARCOMPENSATION,ENJAMBISTE,
    AUTORISEAFAIRELERATTRAPAGE, PASSEENCLASSESSUPERIEURE, OBTIENLEDIPLOME, PASSAGECONDITIONNEL, ENMOBILITE, TERMINEE

}
